image: docker:latest

variables:
  AWS_REGION: ap-southeast-1
  ECR_REPO: 939799150520.dkr.ecr.ap-southeast-1.amazonaws.com

services:
- docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
    - docker build -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME:latest $ECR_REPO/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker tag $CI_PROJECT_NAME:latest $ECR_REPO/$CI_PROJECT_NAME:latest
    - docker push $ECR_REPO/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push $ECR_REPO/$CI_PROJECT_NAME:latest
  when: manual
